### ISSUE TITLE
Question on installation

### ISSUE THREAD

**Issue by muava12** [zsrkmyn/telegram2irc#5]
1. where i should put `telegram2irc` source, in same folder as `tg` or inside `tg` folder ?
2. can i simply install `python-irc` using `sudo pip install irc` or must download the source and place it in specific folder?

**Comment by zsrkmyn** [comment]
1. You may place the source anywhere you want. Simply clone it into you home directory, or a independent directory. XD
2. Sure, you can simply install `python-irc` using `sudo pip install irc` or `sudo pacman -S python-irc` in Arch Linux, but be sure the `pip` installs the python-irc for python3. Maybe `sudo apt-get install python-irc` works in Ubuntu and Debian, but it seems that the `python-irc` packages in these distros is out-of-date (I am not sure about this).
